In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import MDAnalysis as mda
import buckyball_3dmol

In [11]:
gro_file = '../Band3_traj/band3.gro'
xtc_file = '../Band3_traj/band3.xtc'
u = mda.Universe(gro_file,xtc_file)

In [12]:
protein = u.select_atoms('protein')
#print list(protein)

In [13]:
#protein.resnames

In [14]:
gly = protein.select_atoms('resname GLY')
for i in list(gly):
    print i

<Atom 290: N of type N of resname GLY, resid 27 and segid SYSTEM>
<Atom 291: H of type H of resname GLY, resid 27 and segid SYSTEM>
<Atom 292: CA of type C of resname GLY, resid 27 and segid SYSTEM>
<Atom 293: C of type C of resname GLY, resid 27 and segid SYSTEM>
<Atom 294: O of type O of resname GLY, resid 27 and segid SYSTEM>
<Atom 295: N of type N of resname GLY, resid 28 and segid SYSTEM>
<Atom 296: H of type H of resname GLY, resid 28 and segid SYSTEM>
<Atom 297: CA of type C of resname GLY, resid 28 and segid SYSTEM>
<Atom 298: C of type C of resname GLY, resid 28 and segid SYSTEM>
<Atom 299: O of type O of resname GLY, resid 28 and segid SYSTEM>
<Atom 318: N of type N of resname GLY, resid 31 and segid SYSTEM>
<Atom 319: H of type H of resname GLY, resid 31 and segid SYSTEM>
<Atom 320: CA of type C of resname GLY, resid 31 and segid SYSTEM>
<Atom 321: C of type C of resname GLY, resid 31 and segid SYSTEM>
<Atom 322: O of type O of resname GLY, resid 31 and segid SYSTEM>


In [15]:
gly.positions

array([[ 45.65999985,  67.1000061 ,  63.27000046],
       [ 45.70000076,  66.11000824,  63.18000412],
       [ 46.78000641,  67.64000702,  64.12000275],
       [ 47.49000168,  68.8500061 ,  63.44000244],
       [ 47.68000031,  69.87000275,  64.1700058 ],
       [ 47.28000259,  69.01000214,  62.15000153],
       [ 47.15999985,  68.18000031,  61.60000229],
       [ 47.57000351,  70.24000549,  61.28000259],
       [ 46.63999939,  71.53000641,  61.45000458],
       [ 47.11000443,  72.45000458,  62.08000183],
       [ 46.90000153,  72.34999847,  65.06000519],
       [ 47.06000519,  71.44000244,  64.6700058 ],
       [ 48.01000214,  73.34000397,  65.05000305],
       [ 47.83000183,  74.70999908,  64.38000488],
       [ 48.1000061 ,  75.68000031,  65.1000061 ]], dtype=float32)

In [19]:
for ts in u.trajectory[3:4]:
    print ts.time
    print gly.positions

300.0
[[ 44.47000122  66.72000122  64.02000427]
 [ 44.59999847  65.81000519  63.62000275]
 [ 45.69000244  67.27999878  64.6700058 ]
 [ 46.03000259  68.71000671  64.08000183]
 [ 46.63000107  69.49000549  64.81000519]
 [ 45.82000351  68.87000275  62.78000259]
 [ 45.88000488  68.05000305  62.2100029 ]
 [ 45.83000183  70.15000153  62.08000183]
 [ 44.78000259  71.08000183  62.63000488]
 [ 44.99000168  71.96000671  63.4600029 ]
 [ 44.40999985  73.16000366  66.07000732]
 [ 44.69000244  72.48000336  65.40000153]
 [ 45.40000534  74.16000366  66.40000153]
 [ 44.97000122  75.61000061  66.65000153]
 [ 45.45999908  76.21000671  67.58000183]]
